- Task40
artsiomMandrukevich/UnitTesting-master pull request #4
Opened 2022-08-12 12:34 UTC by artsiomMandrukevich

`LogInTest` is a parametrized test for log in.
`MultiSelectTest` is tests for multiselect
`AllertsTest` is tests for alerts
`UserWaiting` is an automated script, which waits for use
`RefreshPage` is an automated script, which refreshes the page when percentage is >= 50
`EmployeesFilter` is an automated script, which returns a list of custom objects with `age > x` and `salary <= y` from Web Table

2022-08-12 17:58 UTC, LikBez123 requested changes

2022-08-12 17:58 UTC, LikBez123 commented on src/test/java/helpers/Element.java
> +public class Element {
remove this class

2022-08-12 17:58 UTC, LikBez123 commented on src/test/java/AllertsTest.java
> +
remove empty lines

2022-08-12 17:58 UTC, LikBez123 commented on src/test/java/MultiSelectTest.java
> +        driver.get("https://demo.seleniumeasy.com/basic-select-dropdown-demo.html");
```
@Test
    public void multiSelect() {
        driver.get("https://demo.seleniumeasy.com/basic-select-dropdown-demo.html");
        Select multiSelect = new Select(driver.findElement(MULTI_SELECT));
        List<String> expectedStates = new Random().ints(3, 0, multiSelect.getOptions().size()).boxed()
                .map(i -> multiSelect.getOptions().get(i).getText()).collect(Collectors.toList());
        expectedStates.forEach(state -> multiSelect.selectByValue(state));
        List<String> selectedStates = multiSelect.getAllSelectedOptions().stream().map(element -> element.getText())
                .collect(Collectors.toList());
        assertTrue(expectedStates.containsAll(selectedStates));
    }
```

2022-08-13 19:48 UTC, artsiomMandrukevich commented on src/test/java/MultiSelectTest.java
> +        driver.get("https://demo.seleniumeasy.com/basic-select-dropdown-demo.html");
done

2022-08-13 19:48 UTC, artsiomMandrukevich commented on src/test/java/AllertsTest.java
> +
done

2022-08-13 19:48 UTC, artsiomMandrukevich commented on src/test/java/helpers/Element.java
> +public class Element {
done

2022-08-15 13:17 UTC, LikBez123 approved these changes

2022-08-16 08:17 UTC, merged